### ISSUE TITLE
Updating to 1.5.2 causes error

### ISSUE THREAD

**Issue by chazsolo** [Aljullu/react-lazy-load-image-component#98]
**Bug description**
Upgrading to 1.5.2 causes a webpack error to be thrown. 1.5.1 works just fine with our webpack version 4.41.6

```
Uncaught TypeError: __webpack_modules__[e] is not a function
    at __webpack_require__ (vendor-React.f420156d1dc70973bea8.js:2:1)
    at Object.react (vendor-React.f420156d1dc70973bea8.js:2:1)
    at __webpack_require__ (vendor-React.f420156d1dc70973bea8.js:2:1)
    at eval (LazyLoadImage.jsx:5:63)
    at Object../src/components/LazyLoadImage.jsx (vendor-React.f420156d1dc70973bea8.js:2:1)
    at __webpack_require__ (vendor-React.f420156d1dc70973bea8.js:2:1)
    at eval (index.js:7:87)
    at Object../src/index.js (vendor-React.f420156d1dc70973bea8.js:2:1)
    at __webpack_require__ (vendor-React.f420156d1dc70973bea8.js:2:1)
    at vendor-React.f420156d1dc70973bea8.js:2:1
```

**To Reproduce**

Update to 1.5.2 and run app using the package

**Technical details:**
- Package version 1.5.2
- Server Side Rendering? No
- Device? All
- Operating System? Mac
- Browser? Chrome

**Comment by TimLehner** [comment]
@Aljullu I believe there is a discrepancy between the source code and the published package. If I take my fork (updated to 1.5.2) and `npm run build` my `build/index.js` is quite different. For example, there are various references to `console.log` in the build directory. I think you accidentally published a development build that wasn't committed. 

@chazsolo in the interim, you can use `@timlehner/react-lazy-load-image-component`. [src](https://github.com/TimLehner/react-lazy-load-image-component)

**Comment by Aljullu** [comment]
My bad. :man_facepalming: 

Should be fixed now, can you test again @chazsolo and @TimLehner?

**Comment by TimLehner** [comment]
That seems to all be working now, thanks @Aljullu. I've marked my fork on npmjs as deprecated now.

**Comment by chazsolo** [comment]
Yes, works for me! Thanks @Aljullu for your quick response!
